### ISSUE TITLE
Implement standard model storage and SHAP evaluator notebook

### ISSUE THREAD

**Issue by rcurrie** [braingeneers/organoid-net#1]
Implement a notebook that ingests models in a standard format (TBD) and uses [SHAP](https://github.com/slundberg/shap) to explain them. This will finish up the workflow to ingest, train, and evaluate data and models efficiently and iteratively.

**Comment by rcurrie** [comment]
Preliminary SHAP display for a single sample with label '12'. Have not validated this but at least there are more things lit on on the 12=12 then the others. Plan to run fashion-mnist through all of it to verify the pipeline and this new drawing code. See [SHAP](https://github.com/slundberg/shap) and the MNIST display for an idea of what's going on - red means the presence lead to the label and blue means the absence (see '4') helped with the label.

@atspaeth @haussler asked about providing some sort of 'key' per image as to which neurons should be litup or identified. For all images with label '12', for example, there output would be slightly different - right? We could generate a 'key' image that I can plot side by side or under the display to see if we're picking up the right things.

![image](https://user-images.githubusercontent.com/492570/48563595-8ac3b980-e8a9-11e8-8279-3f2b7fe6e1e6.png)

**Comment by atspaeth** [comment]
Nice! Now let me see if I understand what is going on here... 

Since SHAP labels regions blue which are negatively correlated with the label you're asking about, what we're seeing is that for each wrong label, two separate regions of cells tell you that it is wrong: the region (here #12) that _is_ lit up and wouldn't be for that label, and the region corresponding to the label you're querying, which is _not_ lit up but should be. 

Then, for the correct label, cells everywhere provide information because outside region 12 most cells are a little less active than average whereas inside region 12 the cells are hyperactive. There is more red than blue because the classification was correct, but there are blue points because some outside cells are more active and some inside cells are less active than expected.

Does that sound about right?

**Comment by haussler** [comment]
That is my understanding as well, but Rob can verify. What Rob didn't
mention but is important is that the neural net predicts which stimulus
produced the cell activity image with 100% accuracy. That is why the focus
is not on accuracy but on how the neural net is doing its job. Alex, you
might give the net some harder problems now that everything is working.

**Comment by atspaeth** [comment]
Absolutely! I would also be interested to see if I upload a new dataset
with the same model and assumptions but a different organoid how accurate
Rob's model as trained on *this* dataset will be.

**Comment by rcurrie** [comment]
The output of the model is a one-hot of 49 values, one for each label. For a given output the red pixels increase the output and the blue pixels decrease the output. In the case of MNIST digit 4:
![image](https://user-images.githubusercontent.com/492570/48567616-4b4d9b00-e8b2-11e8-8ba5-c960d2ca2f89.png)

The red pixels on the 4 label are contributing to that one-hot output. The blue pixels on the 9 label are reducing its output. So for the all lit up label '12' the red I'm thinking indicates which neurons are responding to the stimulus. Caveat is I haven't totally validated this. The images shown are only using a background of ~100 examples as the SHAP calculation takes a while. Using a bigger background is probably warranted - but I also may make the model smaller so it runs faster. Ultimately I think I can create a notebook that can be opened in Colab that you can drag an image onto and it will color it for you.

**Comment by haussler** [comment]
Notebook would be great!

**Comment by rcurrie** [comment]
Trained and ran fashion-mnist to roughly validate all this machinery. Here is the SHAP display for T-Shirt/0 vs. Pullover/2. The sleeves are factoring into the pullover label:
![image](https://user-images.githubusercontent.com/492570/48640363-545e6b00-e98b-11e8-8535-5d3bba003634.png)

**Comment by rcurrie** [comment]
Computed SHAP using a full batch (128 samples) as background and now printing all 49 images. Scroll to the [bottom](https://github.com/braingeneers/organoid-net/blob/27ed57c5a0eaafcaa14f46aa1bb9394fe2cd9f71/simulated/explain.ipynb) to see all of them. One that matches label:

![image](https://user-images.githubusercontent.com/492570/48649498-9dbcb380-e9a7-11e8-9001-17d456a41625.png)

vs. one that is not the label:

![image](https://user-images.githubusercontent.com/492570/48649516-b1681a00-e9a7-11e8-99ca-c2b03a89b14f.png)

**Comment by rcurrie** [comment]
I’ve managed to get the [train](https://colab.research.google.com/drive/1EcTMF9xJjf1F0AeqkvnT7AGoARys2xWu) and [explain](https://colab.research.google.com/drive/1Y1vLZ1Gy0ayw7oP7h-qrRXTacDviqMYx) code running completely in colab notebooks. The initial cells in the explain notebook allow you to upload an example - take one from Alex’s new simulation ([download zip with 8k train + 2k test](https://s3.nautilus.optiputer.net/braingeneers/simulated/newmodel.zip)) to try out. The explain images generated are not quite correct yet in colab, but the one I run locally on PRP does have a reasonably correct set of images (scroll all the say to the bottom). 

NOTE: The train notebook demonstrates how to save the model in your google drive under data/braingeneers so you can later load it in the explain notebook. This is much simpler then using S3 and Kubernetes - all you need is Google Docs!. Although we’ll need some of us to come up the larger engineering system this should allow us to focus on methods initially before all the engineering gets in the way.

Closing as the first step on this is complete towards new issues to take it a few steps further.
